TWITTER_CONSUMER_KEY = "change-me"
TWITTER_CONSUMER_SECRET = "change-me"
LANGUAGE='en'

#Linkedin credentials
LINKEDIN_CLIENT_ID = "change-me"
LINKEDIN_CLIENT_SECRET = "change-me"
LINKEDIN_REDIRECT_URL = "change-me"

TWITTER_CONSUMER_KEY = "9X3Chi8386bl63kDoM6KwoNIx"
TWITTER_CONSUMER_SECRET = "feHAEsMBCSbMdIfhwh3h37z3w23XBYcj4ANBkKkPhx1V1WKgou"
